### ISSUE TITLE
[Bug] - Can't change current season value

### ISSUE THREAD

**Issue by Iveess** [AnthonyMichaelTDM/DRG-Save-Editor#97] opened 2024-07-26 08:22 UTC
### Describe the bug

When I tried to select which season I want to change in the editor, the list did not open and I can’t do anything (other season data I put manually).
![Skillisue](https://github.com/user-attachments/assets/aa0888a6-4a76-4a6c-93c8-744c05ccb9d7)

### To Reproduce

1. Open save file
2. Press CTRL+R to reset my values from save
3. Click on 'Season' list
4. See that nothing happens

### Expected behavior

A list of seasons available to choose from has opened.

### Save File

attached Backup file: 
[Backup.zip](https://github.com/user-attachments/files/16388676/Backup.zip)

### Environment

- OS: Windows 11
- Python Version: 3.12.0

## Checklist

- [x] I know how to use check boxes
- [x] I am using the most recent version of the editor
- [x] I have installed the editor correctly:
  - Check only one:
    - [x] I have installed the editor from the releases page
    - [ ] I an running the editor from source
- [x] If the issue is with editing save files, I attached a copy of my save file from before any edits were attempted
  - **Note**: If you do not attach a save file, it will be significantly harder (and in some cases impossible) to diagnose your issue
- [ ] I have read through relevant Discussions and Issues (including closed ones) and confirm that my issue wasn't resolved previously
- [x] I have filled out the issue template correctly, and to the best of my ability. If I have not, I understand that my issue may be closed with or without a response

**Comment by wahlp** [comment] 2024-07-29 17:40
i get a parsing error on the v1.9.1 build, not even able to load the file you provided and reach the point where you can start changing values

**Comment by simon-wg** [comment] 2024-07-29 18:30
I just looked into this a bit, and it's quite bad.
The parsing error is due to no overclocks being unlocked, and I'm about to open a PR for it now.

However the major issue I found is that it appears the XP values for a season is not hardcoded as we've thought, we use a 169 bit offset for it right now, but his save file is exactly 48 bits from the season marker. Scrips have the same issue where we have it hardcoded to 209, but his are 88 bits from the marker.

I believe this issue also extends to blank cores, since I doubt he has 576495936675512320 blank cores added.

And those are only the ones I can find at a glance, so we might have to change the way we look for season xp and scrip values, to instead search for the first instance of 'XP' and 'Tokens'.

**Comment by simon-wg** [comment] 2024-07-29 18:37
#100 might fix the season select issue if it's caused by a runtime error, and I think the issue with the offsets is caused by trying to edit a save with little progress in the season since the game appears to insert CountSeasonContentEnabled and CountSeasonContentDisabled between the season marker and the XP value at some point.

That or they have changed how the saves work with Update 5.

**Comment by AnthonyMichaelTDM** [comment] 2024-07-29 18:52
48 and 88 were the offsets we used back before you could change seasons, perhaps this is an old save (hasn't been run in the most recent version of DRG)? either way we should figure out a mechanism for determining which offsets to use (perhaps the logic could be "if only 1 season is found, use legacy offsets")

**Comment by simon-wg** [comment] 2024-07-29 19:07
This solution should work in all cases since both the amount of bytes between the key (xp/tokens) and the value should be constant.

**Comment by AnthonyMichaelTDM** [comment] 2024-07-29 19:12
alr, I'll write some tests to validate that and then we can merge

**Comment by AnthonyMichaelTDM** [comment] 2024-07-29 19:23
> Huh, didn't know that. But I've got a PR on the way that should find the offsets by searching for the XP and Token strings, so that should cover all our bases (unless GSG decide to increase the offset even more)

right, and we can always change things again if that does happen

**Comment by AnthonyMichaelTDM** [comment] 2024-07-29 19:52
this was partially fixed in #101 and should be fully fixed once #100 is ready

**Closed** 2024-07-29 22:27 UTC
Labels: Type: Bug, Status: In Progress
