### ISSUE TITLE
[Bug] - Editor still dont work properly after Season 5, now completely. Episode 2: A New Hope

### ISSUE THREAD

**Issue by kiri445566** [AnthonyMichaelTDM/DRG-Save-Editor#92] opened 2024-07-16 15:53 UTC
#42  Report
[#](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/issues/42)
### Describe the bug

@ A clear and concise description of what the bug is, including any error messages you may have received.

Include any relevant screenshots or videos if possible, they can be very helpful in diagnosing the issue.

### Expected behavior

Downloaded from the release link, ran on As of the administrator - 0% of the result. The program just does something and then (maybe before saving) creates a file with a postfix/extension ".old" and nothing happening. There are no changes in the game, but at least the game does not start over, thats maybe god?

### Save File

[SaveGames.zip](https://github.com/user-attachments/files/16253311/SaveGames.zip)

### Environment

- OS: Windows11

## Checklist

- [T] I know how to use check boxes
- [T] I am using the most recent version of the editor
- [T] I have installed the editor correctly:
  - Check only one:
    - [T] I have installed the editor from the releases page
    - [F] I an running the editor from source
- [T] If the issue is with editing save files, I attached a copy of my save file from before any edits were attempted
  - **Note**: If you do not attach a save file, it will be significantly harder (and in some cases impossible) to diagnose your issue
- [T] I have read through relevant Discussions and Issues (including closed ones) and confirm that my issue wasn't resolved previously
- [T] I have filled out the issue template correctly, and to the best of my ability. If I have not, I understand that my issue may be closed with or without a response

**Comment by wahlp** [comment] 2024-07-17 21:31
similar to #91 

sounds like it could be solved by #84 but it's not been put into the executable yet. 
in the meantime, you could try running from the latest source code and see if it works.

**Comment by kiri445566** [comment] 2024-07-17 23:20
> similar to #91
> 
> sounds like it could be solved by #84 but it's not been put into the executable yet. in the meantime, you could try running from the latest source code and see if it works.

maybe you right, i was check this thread and will try to run this into terminal like code.

**Comment by kiri445566** [comment] 2024-07-17 23:21
missclick, sry

**Comment by AnthonyMichaelTDM** [comment] 2024-07-18 21:58
should be fixed in v1.9.1 (building rn)

**Comment by Rukofamicom** [comment] 2024-07-19 00:49
I can confirm that this is fixed in v1.9.1

![image](https://github.com/user-attachments/assets/b2fc899d-558e-4d2d-83ac-a19229524b93)

This issue was preventing me from saving previously

**Comment by kiri445566** [comment] 2024-07-19 16:24
I dont know, are you fixed it later, after I dealt with my problem or before? But for now, everything is working and successful saved. It needs to be installed only as per the video instructions - through the code and open in Power Shell or GIT Bash. Thank you, guys!

A small wish for you: make it possible to change seasons 1 and 2, in addition to the last 3

**Closed** 2024-07-19 16:25 UTC
Labels: Type: Bug, Status: Pending

**Comment by wahlp** [comment] 2024-07-19 18:23
> make it possible to change seasons 1 and 2, in addition to the last 3

ingame, go to the season terminal and change the season to which ones the console say you are missing.
it will update your save file and let you edit data for all seasons.

**Comment by WarmwalkerArts** [comment] 2025-09-29 16:25
Hello! I am currently having this same issue;

>Using the DRG Save Editor with my saves won't save any changes because I am missing Season one
>I followed the tips from this thread; open the game, change the Season to Season 1, save the game and use the save editor
>The saves still stay at Season 5, and the error still persists. I tried the backup versions of the save file to no avail.

I need some help with this issue since I only need to change the Blank Matrix Cores and _that's it_. Hoping for your swift response!
