### ISSUE TITLE
qt.qpa.plugin error

### ISSUE THREAD

**Issue by XomkaShou** [AnthonyMichaelTDM/DRG-Save-Editor#30] opened 2023-07-12 11:52 UTC
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Any ways to fix it?

**Comment by AnthonyMichaelTDM** [comment] 2023-07-12 21:53
make sure you've followed the installation instructions properly, if you still have the issue then give me some steps to reproduce the bug

**Comment by AnthonyMichaelTDM** [comment] 2023-07-31 22:59
if you're on windows, there is a community made installation-tutorial that may help you https://www.youtube.com/watch?v=2h2-nZ2ptRo

**Comment by Mikenek0o** [comment] 2023-09-18 07:02
> if you're on windows, there is a community made installation-tutorial that may help you https://www.youtube.com/watch?v=2h2-nZ2ptRo

so, i run <python ./src/main/python/main.py> happens this:
 <qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.>
in the vid he actually runs <python3 ./src/main/python/main.py> but that didnt help either.
i installed python 3.10 from microsoft store and have no other program.
dunno what to do.

**Comment by Mikenek0o** [comment] 2023-09-20 07:36
> Did you install all the dependencies?
> 
> pip -r requirements.txt
![image](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/assets/145324175/a55fa62a-db3d-4e45-ba34-ee762903208c)

i guess, yeah

**Comment by AnthonyMichaelTDM** [comment] 2023-11-14 23:28
reading that, it seems like you're running python 3.9, see #19

**Comment by oguzzct** [comment] 2024-04-14 11:43
could you get it to work? i'm experiencing the same issue rn

**Comment by AnthonyMichaelTDM** [comment] 2024-07-14 06:28
I'm going to close this, if feel free to re-open if necessary

**Closed by AnthonyMichaelTDM** 2024-07-14 06:28 UTC
Labels: bug, help wanted
